module.exports = {
  auth: require("./auth"),
  duplication: require("./duplication"),
  emailVerification: require("./emailVerification"),
  info: require("./info"),
  kakao: require("./kakao"),
  login: require("./login"),
  logout: require("./logout"),
  passwordVerification: require("./passwordVerification"),
  signup: require("./signup"),
  signupVerification: require("./signupVerification"),
  findPwVerification: require("./findPwVerification"),
  withdrawal: require("./withdrawal"),
  naverLogin: require("./naver"),
};
